[package]
name = "mathroborust-py"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mathroborust = { path = ".." }
nalgebra = "0.32"
pyo3 = { version = "0.23", features = ["extension-module"] }
